openapi: 3.0.3
info:
  title: Cosmo Cats Intergalactic Marketplace API
  description: API for managing cosmic products
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /api/products:
    get:
      summary: Get all products
      tags: [Products]
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      summary: Create new product
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '201':
          description: Product created successfully
        '400':
          description: Validation error

  /api/products/{id}:
    get:
      summary: Get product by ID
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

    put:
      summary: Update product
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '200':
          description: Product updated
        '400':
          description: Validation error

    delete:
      summary: Delete product
      tags: [Products]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Product deleted

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "a1b2c3"
        name:
          type: string
          example: "galaxy milk"
        price:
          type: number
          format: double
          minimum: 0.01
          example: 42.5
        description:
          type: string
          example: "Fresh milk from Milky Way cows"

    ProductCreate:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
          minLength: 3
          example: "star yarn"
        price:
          type: number
          format: double
          minimum: 0.01
          example: 12.99
        description:
          type: string
